# Generated by Django 5.0.6 on 2024-07-02 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
