# Generated by Django 5.0.6 on 2024-07-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0007_rename_orders_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='address1',
        ),
        migrations.AddField(
            model_name='order',
            name='address2',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
